# Generated by Django 4.1.2 on 2022-10-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_customer_clothes_price_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='mainapp', verbose_name='Изображение')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealapp.brand', verbose_name='Бренд')),
            ],
        ),
    ]
