# Generated by Django 4.1.2 on 2022-10-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0005_sneakercard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='sent_at',
        ),
    ]
